version: '3.3'

services:
  api:
    build: .
    ports:
      - '${PORT:-8080}:${APP_PORT:-8080}'
    restart: always
    links:
      - 'cache'
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env

  cache:
    image: redis:${REDIS_TAG:-latest}
    restart: always
    volumes:
      - ./data:/data
